# Generated by Django 5.0.3 on 2024-03-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newspagegalleryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsindexpage',
            name='intro',
        ),
        migrations.AlterField(
            model_name='newspage',
            name='intro',
            field=models.CharField(max_length=500),
        ),
    ]
