# Generated by Django 5.0.3 on 2024-03-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_newstagindexpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='date',
            field=models.DateTimeField(verbose_name='Post date'),
        ),
    ]
