# Generated by Django 5.0.3 on 2024-03-24 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructurePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Substructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substructures', to='structure.structurepage')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='employees')),
                ('position', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('substructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='structure.substructure')),
            ],
        ),
    ]
