# Generated by Django 5.0.3 on 2024-03-24 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substructure',
            name='structure_page',
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivisions', to='structure.structurepage')),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Substructure',
        ),
    ]
