# Generated by Django 5.0.3 on 2024-03-24 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_department_structurepage_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='structurepage',
            name='department',
        ),
    ]
