# Generated by Django 5.0.3 on 2024-03-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0005_remove_department_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='structurepage',
            name='departments',
            field=models.ManyToManyField(blank=True, to='structure.department'),
        ),
    ]
